<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreSpecialOfferRequest;
use App\Http\Requests\Admin\UpdateSpecialOfferRequest;
use App\Http\Resources\SpecialOfferResource;
use App\Jobs\InvalidateCasinoCache;
use App\Models\SpecialOffer;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class SpecialOfferController extends Controller
{
    public function index(): AnonymousResourceCollection
    {
        // Eager-load the casino's attached sites so the admin can build each
        // offer's public single-page link (https://{site domain}/special-offers/{slug}).
        return SpecialOfferResource::collection(
            SpecialOffer::with('casino.sites')->latest()->get()
        );
    }

    public function store(StoreSpecialOfferRequest $request): SpecialOfferResource
    {
        $offer = SpecialOffer::create($request->validated());

        $this->revalidate($offer);

        return new SpecialOfferResource($offer->load('casino.sites'));
    }

    public function show(SpecialOffer $specialOffer): SpecialOfferResource
    {
        return new SpecialOfferResource($specialOffer->load('casino.sites'));
    }

    public function update(UpdateSpecialOfferRequest $request, SpecialOffer $specialOffer): SpecialOfferResource
    {
        $specialOffer->update($request->validated());

        $this->revalidate($specialOffer);

        return new SpecialOfferResource($specialOffer->fresh('casino.sites'));
    }

    public function destroy(SpecialOffer $specialOffer): JsonResponse
    {
        $this->revalidate($specialOffer);

        $specialOffer->delete();

        return response()->json(null, 204);
    }

    public function duplicate(SpecialOffer $specialOffer): SpecialOfferResource
    {
        $copy = $specialOffer->replicate(['slug']);
        $copy->title = $specialOffer->title . ' (Copy)';
        $copy->slug = null; // regenerated by HasSlug
        $copy->save();

        $this->revalidate($copy);

        return new SpecialOfferResource($copy->load('casino.sites'));
    }

    private function revalidate(SpecialOffer $offer): void
    {
        $siteIds = $offer->casino?->sites()->pluck('sites.id')->all() ?? [];

        if (! empty($siteIds)) {
            InvalidateCasinoCache::dispatch($siteIds);
        }
    }
}
