<?php

declare(strict_types=1);

namespace App\Http\Controllers\Api\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreSpecialOfferRequest;
use App\Http\Requests\Admin\UpdateSpecialOfferRequest;
use App\Http\Resources\SpecialOfferResource;
use App\Jobs\InvalidateCasinoCache;
use App\Models\SpecialOffer;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class SpecialOfferController extends Controller
{
    public function index(): AnonymousResourceCollection
    {
        // Eager-load the casino's attached sites so the admin can build each
        // offer's public single-page link (https://{site domain}/special-offers/{slug}).
        return SpecialOfferResource::collection(
            SpecialOffer::with('casino.sites')->latest()->get()
        );
    }

    /**
     * Total special offers, as a dedicated COUNT.
     *
     * Kept off the listing request on purpose: that query eager-loads
     * casino.sites and orders by created_at, and neither has any bearing on the
     * total. This is a bare COUNT against the primary table (soft-deleted rows
     * excluded by the model's global scope).
     */
    public function count(): JsonResponse
    {
        return response()->json(['total' => SpecialOffer::query()->count()]);
    }

    public function store(StoreSpecialOfferRequest $request): SpecialOfferResource
    {
        $offer = SpecialOffer::create($request->validated());

        $this->revalidate($offer);

        return new SpecialOfferResource($offer->load('casino.sites'));
    }

    public function show(SpecialOffer $specialOffer): SpecialOfferResource
    {
        return new SpecialOfferResource($specialOffer->load('casino.sites'));
    }

    public function update(UpdateSpecialOfferRequest $request, SpecialOffer $specialOffer): SpecialOfferResource
    {
        // Captured BEFORE the write. The model's saving hook regenerates the slug
        // whenever the title changes, and the casino may be reassigned — so after
        // update() the old detail-page tag and the previous casino's sites are
        // unreachable, and the pages they back would keep serving the stale offer
        // for the rest of the ISR window.
        $previousSiteIds = $this->siteIdsFor($specialOffer);
        $previousSlug = (string) $specialOffer->slug;

        $specialOffer->update($request->validated());

        $this->revalidate($specialOffer, $previousSiteIds, [$previousSlug]);

        return new SpecialOfferResource($specialOffer->fresh('casino.sites'));
    }

    public function destroy(SpecialOffer $specialOffer): JsonResponse
    {
        // Resolve the audience first, delete, THEN revalidate. Pinging before the
        // delete lets Next.js regenerate the affected pages while the offer is
        // still readable, which re-caches the very rows this request removes.
        $siteIds = $this->siteIdsFor($specialOffer);
        $slug = (string) $specialOffer->slug;

        $specialOffer->delete();

        $this->dispatchInvalidation($siteIds, [$slug]);

        return response()->json(null, 204);
    }

    public function duplicate(SpecialOffer $specialOffer): SpecialOfferResource
    {
        $copy = $specialOffer->replicate(['slug']);
        $copy->title = $specialOffer->title . ' (Copy)';
        $copy->slug = null; // regenerated by the model's saving hook
        $copy->save();

        $this->revalidate($copy);

        return new SpecialOfferResource($copy->load('casino.sites'));
    }

    /**
     * Sites this offer is published on, via its casino's attachments.
     *
     * @return list<int>
     */
    private function siteIdsFor(SpecialOffer $offer): array
    {
        return $offer->casino?->sites()->pluck('sites.id')->all() ?? [];
    }

    /**
     * @param  list<int>     $alsoSiteIds  Sites the offer was on BEFORE this write.
     * @param  list<string>  $alsoSlugs    Detail-page slugs it answered to before.
     */
    private function revalidate(SpecialOffer $offer, array $alsoSiteIds = [], array $alsoSlugs = []): void
    {
        $this->dispatchInvalidation(
            [...$this->siteIdsFor($offer), ...$alsoSiteIds],
            [(string) $offer->slug, ...$alsoSlugs],
        );
    }

    /**
     * @param  list<int>     $siteIds
     * @param  list<string>  $slugs
     */
    private function dispatchInvalidation(array $siteIds, array $slugs): void
    {
        $siteIds = array_values(array_unique(array_filter($siteIds)));

        if ($siteIds === []) {
            return;
        }

        // Every surface an offer appears on, or a visibility toggle would
        // keep showing the card for up to an hour of stale ISR:
        //  - casinos          → the offer cards on the casino page
        //  - special-offers   → the home-page section and /special-offers
        //  - special-offer:*  → the offer's own detail page
        $slugTags = array_map(
            static fn (string $slug): string => 'special-offer:' . $slug,
            array_values(array_unique(array_filter($slugs, static fn (string $s): bool => $s !== ''))),
        );

        InvalidateCasinoCache::dispatch($siteIds, ['casinos', 'special-offers', ...$slugTags]);
    }
}
